package macro303.dh2e

enum class Quirk {
	`Hairy Knuckles`,
	`Joined Eyebrows`,
	Warpaint,
	`Huge Hands`,
	`Filed Teeth`,
	`Beetling Brows`,
	`Musky Smell`,
	Hairy,
	`Ripped Ears`,
	`Long Fingernails`,
	`Tribal Tattooing`,
	Scarring,
	`Pierced Nose`,
	`Cat's Eyes`,
	`Small Head`,
	`Thick Jaw`,
	`Radiation Scar`,
	`Large Head`,
	`Mechanicum Tattoo`,
	`Crooked Nose`,
	`Metallic Smell`,
	`Small Eyes`,
	`Soot-Stained Skin`,
	`Acid Burns`,
	`Missing Eyebrows`,
	`Wheezing Speech`,
	`Missing One Ear`,
	`Smashed Toe`,
	`Squinted Eyes`,
	`Short Fingers`,
	`Wire Grill Over Eyes`,
	`Discoloured Fingernail`,
	`Missing Fingertip`,
	`Aquiline Nose`,
	`Bright White Teeth`,
	`Duelling Scar`,
	`Shiny Hair`,
	`Aquila Tattoo`,
	`Perfumed Odour`,
	`Pox Marks`,
	`Devotional Scar`,
	`Decorative Electoo`,
	`Quivering Fingers`,
	`Pierced Ears`,
	`Sinister Boil`,
	`Sharp Cheekbones`,
	`Slouched Gait`,
	`Thin Lips`,
	`Grimy Skin`,
	`Painted Fingernails`,
	`Rotten Teeth`,
	`Faded Electoo`,
	`Pierced Eyebrow`,
	`Wire Mesh Along Cheek`,
	`Hacking Cough`,
	`Tattoo Over One Eye`,
	`Bullet Wound Scar`,
	`Nervous Tic`,
	`Large Mole`,
	`Pollution Scars`,
	Hump,
	`Small Hands`,
	`Chemical Smell`,
	`Heavy Brows`,
	`Long Nose`,
	`Ministorum Tattoo`,
	`Ridged Fingernails`,
	`Crooked Teeth`,
	`Clefted Chin`,
	`Dry Skin`,
	`Thick Eyebrows`,
	`Ink-Stained Fingernails`,
	`Shrivelled Ear`,
	`Ritual Scars`,
	`Third Nipple`,
	`Bloodshot Eyes`,
	`Mouldy Scent`,
	`Winestain Birthmark`,
	`Broad Shoulders`,
	`Long Toes`,
	`Fine Hair`,
	`Long Fingers`,
	`Tiny Ears`,
	`Spindly Limbs`,
	`Yellow Fingernails`,
	`Stumpy Teeth`,
	`Widely Spaced Eyes`,
	`Curved Spine`,
	Hairless,
	`Elegant Hands`,
	`Slightly Cross-Eyed`,
	`Webbed Toes`,
	`Minor Limp`,
	`Mismatched Eyes`
}